/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data_base;

import application.Base_de_donnee;
import application.Parametre;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import application.ResultSetTableModel;
/**
 *
 * @Raed Jaidi
 */
public class Produit extends javax.swing.JFrame {

    /**
     * Creates new form Produit
     */
      ResultSet res;
    Base_de_donnee bd;
    public Produit() {
            bd=new  Base_de_donnee(new Parametre().HOST_BD,new Parametre().USER_NAME_BD,
                new Parametre().PASSWORD_BD,new Parametre().IP_HOST, new Parametre().PORT);
        initComponents();
        table();
    }
/////////////////////////////////////////////Raed Jaidi///////////////////////////////////////////////////
    public void table(){
        String a[]= {"id","code_produit","fournissuer","prix","stock"};
        res=bd.querySelect(a,"utilisateur");
        table_produit.setModel(new ResultSetTableModel(res));
    }
/////////////////////////////////////////////Raed Jaidi///////////////////////////////////////////////////
    void actualiser(){
    txt_code_produit.setText("");   
    txt_fournisseur.setText(""); 
    txt_prix.setText(""); 
    txt_stock.setText("");
    
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_produit = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_code_produit = new javax.swing.JTextField();
        txt_fournisseur = new javax.swing.JTextField();
        txt_prix = new javax.swing.JTextField();
        txt_stock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        txt_recherche_produit = new javax.swing.JTextField();
        jComboBox1_recherche_raed = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_produit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "code_produit", "fournissuer", "prix", "stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_produit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_produitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_produit);

        jLabel1.setText("Gestion de produit");

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Actualiser");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("code produit:");

        jLabel3.setText("fournisseur:");

        jLabel4.setText("prix:");

        jLabel5.setText("stock:");

        txt_prix.setText("jTextField3");

        txt_stock.setText("jTextField4");

        jLabel6.setText("recherche par catégorie:");

        jButton5.setText("recherche");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txt_recherche_produit.setText("jTextField1");

        jComboBox1_recherche_raed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "code_produit", "prix", "stock" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_code_produit, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_fournisseur, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_prix, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_recherche_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(32, 32, 32)
                                        .addComponent(jButton4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1_recherche_raed, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_code_produit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1_recherche_raed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_fournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(txt_recherche_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(txt_code_produit.getText().equals("") || txt_fournisseur.getText().equals("") ||
        txt_prix.getText().equals("") || txt_stock.getText().equals("")) 
         JOptionPane.showMessageDialog(this,"entrer les informations complete!");
         else
        { String[] col= {"id","code_produit","fournissuer","prix","stock"};
         String[] inf={txt_code_produit.getText(),txt_fournisseur.getText(),txt_prix.getText(),
        txt_stock.getText()};
         System.out.println(bd.queryInsert("utilisateur",col,inf));
         table();
         actualiser();
        
         }
    }//GEN-LAST:event_jButton1ActionPerformed
/////////////////////////////////////////////Raed Jaidi///////////////////////////////////////////////////
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(txt_code_produit.getText().equals("") || txt_fournisseur.getText().equals("") ||
           txt_prix.getText().equals("") || txt_stock.getText().equals("")) 
           JOptionPane.showMessageDialog(this,"entrer les informations complete!");
           else
           { String[] col= {"id","code_produit","fournissuer","prix","stock"};
              String[] inf={txt_code_produit.getText(),txt_fournisseur.getText(),txt_prix.getText(),
             txt_stock.getText()};
             String id= String.valueOf(table_produit.getValueAt(table_produit.getSelectedRow(),0));
             System.out.println(bd.queryUpdate("utilisateur",col,inf,"id='"+id+"'"));
              table();
              actualiser();
           }
    }//GEN-LAST:event_jButton2ActionPerformed
/////////////////////////////////////////////Raed Jaidi///////////////////////////////////////////////////
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String id= String.valueOf(table_produit.getValueAt(table_produit.getSelectedRow(),0));
        if( JOptionPane.showConfirmDialog(this,"Suppression!","attension",
          JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
        bd.queryDelete(id);
        else 
            return;
        table();
    }//GEN-LAST:event_jButton3ActionPerformed
/////////////////////////////////////////////Raed Jaidi///////////////////////////////////////////////////
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        actualiser();
        table();
    }//GEN-LAST:event_jButton4ActionPerformed
/////////////////////////////////////////////Raed Jaidi///////////////////////////////////////////////////
    private void table_produitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_produitMouseClicked
        // TODO add your handling code here:
        txt_code_produit.setText(String.valueOf(table_produit.getValueAt(table_produit.getSelectedRow(),1)));
        txt_fournisseur.setText(String.valueOf(table_produit.getValueAt(table_produit.getSelectedRow(),2)));
        txt_prix.setText(String.valueOf(table_produit.getValueAt(table_produit.getSelectedRow(),3)));
        txt_stock.setText(String.valueOf(table_produit.getValueAt(table_produit.getSelectedRow(),4)));
    }//GEN-LAST:event_table_produitMouseClicked
/////////////////////////////////////////////Raed Jaidi///////////////////////////////////////////////////
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          if(txt_recherche_produit.getText().equals(""))
        JOptionPane.showMessageDialog(this,"Entrer un critere de recherche!");  
        else
        { if( jComboBox1_recherche_raed.getSelectedItem().equals("id"))
              res= bd.querySelectAll("produit" ,"id='" + txt_recherche_produit.getText()
                 +table_produit.setModel(new ResultSetTableModel(res));
         
         else if ( jComboBox1_recherche_raed.getSelectedItem().equals("code_produit"))
              res= bd.querySelectAll("produit" ,"code_produit='" + txt_recherche_produit.getText()
                 +table_produit.setModel(new ResultSetTableModel(res));
         else if ( jComboBox1_recherche_raed.getSelectedItem().equals("prix"))
              res= bd.querySelectAll("produit" ,"prix='" + txt_recherche_produit.getText()
                 +tableproduit.setModel(new ResultSetTableModel(res));
               else if ( jComboBox1_recherche_raed.getSelectedItem().equals("stock"))
              res= bd.querySelectAll("produit" ,"stock='" + txt_recherche_produit.getText()
                 +table_produit.setModel(new ResultSetTableModel(res));
        }  
    }//GEN-LAST:event_jButton5ActionPerformed
/////////////////////////////////////////////Raed Jaidi///////////////////////////////////////////////////
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produit().setVisible(true);
            }
        });
    }
/////////////////////////////////////////////Raed Jaidi///////////////////////////////////////////////////
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1_recherche_raed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_produit;
    private javax.swing.JTextField txt_code_produit;
    private javax.swing.JTextField txt_fournisseur;
    private javax.swing.JTextField txt_prix;
    private javax.swing.JTextField txt_recherche_produit;
    private javax.swing.JTextField txt_stock;
    // End of variables declaration//GEN-END:variables
}
